# GitHub Pages Configuration
title: "RM4Health Dashboard"
description: "Plataforma Profissional de Análise de Dados REDCap"
url: "https://filipepaulista12.github.io"
baseurl: "/rm4health-dashboard"

# Jekyll Settings
markdown: kramdown
highlighter: rouge
theme: minima

# SEO
author: "RM4Health Team"
twitter_username: rm4health
github_username: filipepaulista12

# Build settings
exclude:
  - app.py
  - data_processor.py
  - config.py
  - redcap_client.py
  - requirements.txt
  - templates/
  - .gitignore

# Include files
include:
  - index.html
  - README.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections_dir: collections
